version: '3.5'
services:
  my-password-gen:
    image: local-my-password-gen
    container_name: my-password-gen-api
    volumes:
      - jvazquez.xyz:/my-password-gen
    ports:
      - 8000:8000

networks:
  default:
    external:
      name: jvazquez.xyz
volumes:
  jvazquez.xyz:
    external: true
