version: '3.5'
services:
  my-password-gen:
    image: local-my-password-gen
    container_name: my-password-gen-api
    volumes:
      - develop.jvazquez:/app
networks:
  default:
    external:
      name: my-password-gen-net
volumes:
  develop.jvazquez:
    external: true
