version: '3.5'
services:
  my-password-gen:
    image: local-my-password-gen
    container_name: my-password-gen-api
    volumes:
      - j-vazquez.com:/app
    working_dir: /app/my-password-gen/cmd
    command: ["go", "run", "xkcd.go"]

networks:
  default:
    external:
      name: j-vazquez.com
volumes:
  j-vazquez.com:
    external: true
