version: '3.5'
services:
  my-password-gen:
    image: local-my-password-gen
    container_name: my-password-gen-api
    volumes:
      - my-password-gen-go:/my-password-gen
    ports:
      - 8000:8000

networks:
  default:
    external:
      name: j-vazquez.com
volumes:
  j-vazquez.com:
    external: true
